Update PlotAddNFT.tsx
Chia-Network/chia-blockchain-gui pull request #1671
Opened 2023-04-12 07:36 UTC by Voodoo-Chia

Made the option less likely to cause users to make OG plots by mistake

Changed: "join a pool (Optional)" 
-> "Make plots portable to pools (Cannot be changed later)"

Changed: "Select your Plot NFT from the dropdown or create a new one" -> Select your Plot NFT from the dropdown or create a new one. If you do not select a plot NFT, the plots you make cannot be used with standard pools later on [Learn more]" -> added link to pooling-user-guide

2023-04-17 17:36 UTC, paninaro commented on packages/gui/src/components/plot/add/PlotAddNFT.tsx
> +            <Trans>Make plots portable to pools</Trans>
Can we change this to read:

```suggestion
            <Trans>Plot to a Plot NFT</Trans>
```

2023-04-17 17:37 UTC, paninaro commented on packages/gui/src/components/plot/add/PlotAddNFT.tsx
> +            <Trans>(Cannot be changed later)</Trans>
```suggestion
            <Trans>(Recommended)</Trans>
```

2023-04-17 18:41 UTC, paninaro commented on packages/gui/src/components/plot/add/PlotAddNFT.tsx
> +            </Trans>
```suggestion
            <Trans>
              Plotting to a Plot NFT allows you the flexibility to join a pool or solo farm. You can easily switch
              between different pools or solo farming at any time. If you choose not to plot to a Plot NFT, you will
              need to replot in order to join any of the standard pools.
            </Trans>
            &nbsp;
            <Link target="_blank" href="https://docs.chia.net/pool-farming">
              <Trans>Learn more</Trans>
            </Link>
```

2023-04-17 18:43 UTC, paninaro requested changes
Can you add an import for the `Link` component from `@chia-network/core`?

e.g.
```typescript
import { Button, CardStep, Select, Flex, Link, Loading } from '@chia-network/core';
```

2023-04-17 18:44 UTC, paninaro commented
Thanks for the contribution! I've suggested some minor tweaks based on feedback from the team.

2023-04-18 09:10 UTC, Voodoo-Chia commented
> Can you add an import for the `Link` component from `@chia-network/core`?
> 
> e.g.
> 
> ```ts
> import { Button, CardStep, Select, Flex, Link, Loading } from '@chia-network/core';
> ```

Not really, apart from changing text, I don't really know what I'm doing XD
I just copied the link format from one of the other parts on the same page.

2023-04-21 21:57 UTC, paninaro approved these changes
lgtm

2023-04-21 21:58 UTC, paninaro approved these changes

2023-04-21 21:58 UTC, merged

2023-04-22 07:22 UTC, Voodoo-Chia commented
ah lol, that was easy, tnx Jeff