Add clawback feature to the GUI
Chia-Network/chia-blockchain-gui pull request #1802
Opened 2023-05-30 11:20 UTC by zsolt-dev

Texts are not final yet, but code is ready for feedback.

2023-05-30 18:28 UTC, seeden requested changes

2023-05-30 18:28 UTC, seeden commented on packages/api/src/@types/PuzzleDecorator.ts
> +type PuzzleDecorator = PuzzleDecoratorItem[];
Best practice in Typesscript is define single item and not whole array as type.
You should always use type with array in your function.

2023-05-30 18:28 UTC, seeden commented on packages/gui/src/components/settings/Settings.tsx
> +    if (path.endsWith('/*')) {
why we are doing it?

2023-05-30 18:28 UTC, seeden commented on packages/gui/src/components/settings/Settings.tsx
> +                        top: '-10px',
you can use number -0.625 instead string 10px

2023-05-30 18:28 UTC, seeden commented on packages/gui/src/components/settings/SettingsCustody.tsx
> +      <div>
please remove div, br and other non material-ui tags

2023-05-30 18:28 UTC, seeden commented on packages/gui/src/components/settings/SettingsCustodyAutoClaim.tsx
> +                    top: '-5px',
use numbers instead of 'px'

2023-05-30 18:28 UTC, seeden commented on packages/gui/src/components/settings/SettingsCustodyAutoClaim.tsx
> +                        stroke: '#3AAC59',
can we use colors from theme ?

2023-06-05 17:49 UTC, paninaro approved these changes

2023-06-05 17:50 UTC, merged