Use lerna 7.1.3 and nx 16.3.2 for macos 10.14 building
Chia-Network/chia-blockchain-gui pull request #1917
Opened 2023-07-20 16:56 UTC by emlowe

Use lerna 7.1.3 and nx 16.3.2 for macos 10.14 building

2023-07-20 17:05 UTC, wjblanke submitted a review, later dismissed
aok

2023-07-20 23:47 UTC, paninaro requested changes
Holding off on merging this to see if updating the build scripts is sufficient

2023-07-25 20:35 UTC, paninaro submitted a review, later dismissed

2023-07-25 20:38 UTC, paninaro approved these changes

2023-07-25 20:50 UTC, merged