Adding Walletconnect endpoints for DIDs, Datalayer, and NFT Bulk Mint
Chia-Network/chia-blockchain-gui pull request #2308
Opened 2024-03-18 00:22 UTC by Gaerax

Added a walletconnect endpoints for almost all DID and Datalayer commands, and nft_mint_bulk and push_tx to enable bulk minting via WC, and creating feature rich dapps.

2024-03-20 05:17 UTC, Gaerax commented
I also added an endpoint to allows an app to request permissions for a list commands. This would make for a much better user experience for dapps that require use of many commands, as the user can just be prompted once, at app launch to give permissions for all of the basic, read-only commands that it needs.

This includes a new confirm dialog, which could probably be improved, but it does the job.
![image](https://github.com/Chia-Network/chia-blockchain-gui/assets/98060724/9487468f-a1ec-4cb2-8234-aff6a0d685de)

If the app already has all of the permissions in the list, the command returns successful without prompting the user.

If the command list sent by the app contains a command that does not allow bypass, or is not a valid command name, it is ignored.

2024-03-20 05:28 UTC, Gaerax commented
Since updating my repo with recent commits for the PR, I have found that some of the new WC commands which used to work fine, now have issues. I will switch this PR to a draft for the time being, until I figure out why that is.

2024-03-25 05:26 UTC, Gaerax commented
There was no issue, I'm just a dumb dumb who forgot to run the build command

2024-04-03 14:11 UTC, ChiaMineJP commented
Thank you for the great PR!
Please give us time to review. We'll check the code.

2024-04-04 15:07 UTC, ChiaMineJP requested changes
I've just finished a part of reviewing. I'll do more check later.

2024-04-04 15:07 UTC, ChiaMineJP commented on packages/api-react/src/services/wallet.ts
> +      providesTags: (result, _error, { walletId }) => (result ? [{ type: 'DIDMetadata', id: walletId }] : []),
The tag name `DIDMetadata` should be added to line#10 `tagTypes` array.

2024-04-04 15:07 UTC, ChiaMineJP commented on packages/api-react/src/services/wallet.ts
> +        { type: 'DIDWallet', id: walletId },
`{ type: 'DIDMetadata', id: walletId}` should be added.

2024-07-15 18:07 UTC, emlowe commented
Closing PR - @Gaerax if you want to respond to the code change requests you can do so and reopen the PR

2024-07-15 18:07 UTC, closed without merging