integrate chia tools and log viewer
Chia-Network/chia-blockchain-gui pull request #2565
Opened 2024-12-30 19:04 UTC by BrandtH22

2025-01-02 00:08 UTC, ChiaAutomation commented
Your commits are not signed and our branch protection rules require signed commits. For more information on how to create signed commits, please visit this page: https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification. Please use the button towards the bottom of the page to close this pull request and open a new one with signed commits.

2025-01-07 15:04 UTC, ChiaMineJP commented on packages/gui/src/components/chiatools/logViewer/LogViewer.tsx
> +
While `nodeIntegration` is set to `true` in creating browser window, we usually offload functions, that are not expected to run on web browser, to electron's main process from renderer process for security.

Please see how we let electron main process handle local files and pass data to renderer process in `packages/gui/src/electron/{main.tsx, preload.js}`.

2025-01-18 03:33 UTC, BrandtH22 commented on packages/gui/src/components/chiatools/logViewer/LogViewer.tsx
> +
@ChiaMineJP  This has now been refactored, let me know if that is more along the lines of what we need 👍

2025-01-18 07:15 UTC, ChiaMineJP requested changes

2025-01-18 07:15 UTC, ChiaMineJP commented on packages/gui/src/components/chiatools/logViewer/LogViewerToolbar.tsx
> +  );
Generating a new debounce function and cancelling old one everytime user inputs is a bit inefficient.

I suggest the following code:
```typescript
const debouncedFilterFunc = useMemo(() => {
  return debounce((filterText: string) => {
    onFilterChange({
      ...filter,
      searchText: filterText,
    });
  }, 300);
}, [filter, onFilterChange]);
...
useEffect(() => () => {
  debouncedFilterFunc.cancel();
}, [debouncedFilterFunc]);
```

2025-01-18 07:15 UTC, ChiaMineJP commented on packages/gui/src/electron/main.tsx
> +      const logPath = path.join(chiaRoot, 'log', 'debug.log');
There are users like me who set custom log file location like `log/full_node.log`, `log/wallet.log`, `log/farmer.log` and so on.

So log file location should be loaded and parsed from config file.

2025-01-18 07:15 UTC, ChiaMineJP commented on packages/gui/src/electron/main.tsx
> +      const logPath = path.join(logDir, 'debug.log');
The same as above. There can be users who set their custom log locations.

2025-01-21 18:47 UTC, ChiaMineJP requested changes

2025-01-21 18:47 UTC, ChiaMineJP commented on packages/gui/src/components/chiatools/logViewer/LogViewer.tsx
> +        error?: string;
- `error?: string` should be `fileError?: string;`
- `defaultPath?: string;` is missing here.

2025-01-21 18:47 UTC, ChiaMineJP commented on packages/gui/src/components/chiatools/logViewer/LogViewer.tsx
> +        readable: boolean;
`readable` should be optional.

2025-01-21 18:47 UTC, ChiaMineJP commented on packages/gui/src/components/chiatools/logViewer/LogViewer.tsx
> +      <Flex flexDirection="column" gap={2}>
## Padding should be added
![image](https://github.com/user-attachments/assets/86219c9d-b022-4cb0-95f1-365fba3d1cb0)

### Code suggestion
```typescript
<Flex flexDirection="column" gap={2} padding={2}>
...
```

2025-01-21 21:01 UTC, BrandtH22 commented on packages/gui/src/components/chiatools/ChiaToolsErrorBoundary.tsx
> +export default class ChiaToolsErrorBoundary extends Component<Props, State> {
Thank you, I was using this during dev and have now removed it

2025-01-21 21:01 UTC, BrandtH22 commented on packages/gui/src/components/chiatools/logViewer/LogViewer.tsx
> +}
Thank you, I did a bit of a refactor to this end. Let me know if more is needed

2025-01-21 21:01 UTC, BrandtH22 commented on packages/gui/src/components/chiatools/logViewer/LogViewer.tsx
> +        key={`highlight-${part}-${Math.random().toString(36).substr(2, 9)}`}
Resolved both of these

2025-01-21 21:01 UTC, BrandtH22 commented on packages/gui/src/components/chiatools/logViewer/LogViewerToolbar.tsx
> +  );
refactored the debounce to use this code

2025-01-21 21:11 UTC, BrandtH22 commented on packages/gui/src/components/chiatools/logViewer/LogViewer.tsx
> +        readable: boolean;
resolved in type fixes

2025-01-21 21:11 UTC, BrandtH22 commented on packages/gui/src/components/chiatools/logViewer/LogViewer.tsx
> +      <Flex flexDirection="column" gap={2}>
resolved in formatting fixes

2025-01-22 14:47 UTC, ChiaMineJP approved these changes

2025-01-22 14:49 UTC, merged